// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj0t0qZq4uo3v7WlPGw2pIrU3rvtrgpY8',
    appId: '1:775632908947:web:2340428d474aa4b974d366',
    messagingSenderId: '775632908947',
    projectId: 'quiet-silent',
    authDomain: 'quiet-silent.firebaseapp.com',
    storageBucket: 'quiet-silent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAAwweH4TvxrMVaokjRShIGvZdqeuhu8c',
    appId: '1:775632908947:android:cae64e2f19a1a30f74d366',
    messagingSenderId: '775632908947',
    projectId: 'quiet-silent',
    storageBucket: 'quiet-silent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDHIt3z_Ku0uONk3JorTqZvhxKHtiARw',
    appId: '1:775632908947:ios:5495a5638df6d74874d366',
    messagingSenderId: '775632908947',
    projectId: 'quiet-silent',
    storageBucket: 'quiet-silent.appspot.com',
    iosBundleId: 'com.example.quietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxDHIt3z_Ku0uONk3JorTqZvhxKHtiARw',
    appId: '1:775632908947:ios:5495a5638df6d74874d366',
    messagingSenderId: '775632908947',
    projectId: 'quiet-silent',
    storageBucket: 'quiet-silent.appspot.com',
    iosBundleId: 'com.example.quietApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj0t0qZq4uo3v7WlPGw2pIrU3rvtrgpY8',
    appId: '1:775632908947:web:7f258d31e839a03f74d366',
    messagingSenderId: '775632908947',
    projectId: 'quiet-silent',
    authDomain: 'quiet-silent.firebaseapp.com',
    storageBucket: 'quiet-silent.appspot.com',
  );

}